$font = Iosevka Nerd Font Mono

$bg        = rgba(1c1b19ee)
$fg        = rgba(e6dac4ff)
$accent    = rgba(7890a0ff)
$accent2   = rgba(988090ff)
$red       = rgba(b8524aff)
$green     = rgba(80a090ff)
$border    = rgba(5c574caa)
$placeholder = rgba(746d5fff)

general {
    hide_cursor = false
    ignore_empty_input = true
}

background {
    monitor =
    path = /home/jakepys/.config/wallpapers/hypr_wall/angel_debil.png
    blur_passes = 3
    blur_size = 7
    noise = 0.02
    contrast = 0.9
    brightness = 0.6
    vibrancy = 0.2
    vibrancy_darkness = 0.3
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = $fg
    font_size = 92
    font_family = $font
    position = 0, 180
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d de %B")"
    color = $accent
    font_size = 20
    font_family = $font
    position = 0, 90
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = $fg
    font_size = 18
    font_family = $font
    position = 0, -20
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 55
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.25
    dots_center = true
    outer_color = $border
    inner_color = $bg
    font_color = $fg
    fade_on_empty = false
    placeholder_text = <span foreground="##746d5f">Password...</span>
    hide_input = false
    check_color = $green
    fail_color = $red
    fail_text = <span foreground="##b8524a">Incorrect</span>
    capslock_color = $accent2
    position = 0, -90
    halign = center
    valign = center
    font_family = $font
}
